Fix throw of PackagingException on invalid nullable bool
Call `NuspecReader.GetContentFiles` on AppLoggerSenner007 1.1.8 (available on NuGet.org) to reproduce this error. It is because `Strings.InvalidNuspecEntry` has two format placeholders, not one.

```
An exception occurred.
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object arg0)
   at NuGet.Packaging.NuspecReader.AttributeAsNullableBool(XElement element, String attributeName)
   at NuGet.Packaging.NuspecReader.GetContentFiles()+MoveNext()
```