Removed dead code generating compiler error
Build of NuGet.Clients.sln keeps failing in VS 2017 RC
because of the following compilation error:

> NuGetPowerShellBaseCommand.cs(50,44): error CS0649: Field
'NuGetPowerShellBaseCommand._httpClientEvents' is never assigned to, and will always have its default value null [X:\NuGet.Client\src\NuGet.Clients\PackageManagement.PowerShellCmdlets\NuGet.PackageManagement.PowerShellCmdlets.csproj]

Apparently this field is not used anywhere. Therefore I went ahead and
removed all the dead code failing to compile.